### ISSUE TITLE
Add login with kgp mail

### ISSUE THREAD

**Issue by themousepotato** [metakgp/TravelKGP#55]
A mandatory fb login won't help people without fb. It would be awesome to add login with kgp mail id. You can refer https://github.com/DefCon-007/rateMyProfessor for motivation.

**Comment by aribalam** [comment]
It would be really awesome to have such a feature. Although I added fb as a login medium so that we would be able to identify users through their profile pictures. This is particularly useful in cases where two users share the same name.

**Comment by thealphadollar** [comment]
A better feature would be making login using Google OAuth, KGP email is not good at all.
